version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/gustavorocha11/users-crud
    container_name: users-crud-mvc-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/users-crud-mvc
    volumes:
      - users-crud-mvc:/var/lib/postgresql/data

volumes:
  users-crud-mvc:
